# IP와 PORT는 가변적

### welcome
GET 127.0.0.1:8000/user-service/welcome
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZmM2MjBmZS04ZDMwLTRiZjktODJkNC1hZGQ0ZDllNTY4ZTIiLCJleHAiOjE2NjMyNTMwNzJ9.CH35I71lyt2FMcnqiGxehIXlz0s7vZM3CxIRwySq1zDcH2frsdd6rlVAajCT4qmKfz9BpkTtSl-JEnH1i4XgkA

### healthcheck
GET 127.0.0.1:8000/user-service/health_check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZmM2MjBmZS04ZDMwLTRiZjktODJkNC1hZGQ0ZDllNTY4ZTIiLCJleHAiOjE2NjMyNTMwNzJ9.CH35I71lyt2FMcnqiGxehIXlz0s7vZM3CxIRwySq1zDcH2frsdd6rlVAajCT4qmKfz9BpkTtSl-JEnH1i4XgkA

### actuator health
GET http://172.30.1.4:55581/actuator/health

### actuator beans
GET http://172.30.1.4:55581/actuator/beans

### actuator refresh
POST http://172.30.1.4:55581/actuator/refresh

### gateway 통해 actuator 호출 - health
GET 127.0.0.1:8000/actuator/health
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkNTUxZDI5My00NDNkLTRhNDEtOGE5ZS0yOTgwN2RmNTk2MmQiLCJleHAiOjE2NjIyMDkyOTF9.Npiybr47RBNQIBS4CKKZYvcuqu6-Ger2Uu2TehbmBBhlfcgZiforLHnDC9PxiXQUC3vcbp3Faqn8gh7bH729yw

### gateway 통해 actuator 호출 - health2
GET 127.0.0.1:8000/user-service/actuator/health
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkNTUxZDI5My00NDNkLTRhNDEtOGE5ZS0yOTgwN2RmNTk2MmQiLCJleHAiOjE2NjIyMDkyOTF9.Npiybr47RBNQIBS4CKKZYvcuqu6-Ger2Uu2TehbmBBhlfcgZiforLHnDC9PxiXQUC3vcbp3Faqn8gh7bH729yw

### gateway 통해 actuator 호출 - refresh
POST 127.0.0.1:8000/user-service/actuator/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkNTUxZDI5My00NDNkLTRhNDEtOGE5ZS0yOTgwN2RmNTk2MmQiLCJleHAiOjE2NjIyMDkyOTF9.Npiybr47RBNQIBS4CKKZYvcuqu6-Ger2Uu2TehbmBBhlfcgZiforLHnDC9PxiXQUC3vcbp3Faqn8gh7bH729yw

### gateway 통해 actuator 호출 - refresh2
POST 127.0.0.1:8000/actuator/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2ZTMzZDNjYy03YTkxLTRmYWYtODBjYi02OTUwNmZmYjdmZDkiLCJleHAiOjE2NjIxMzE3ODF9.MS65u-i_IUbvqPEO-Aea9CaZbker8bZKs5PlJaU0vyvp8t9eQKIzP3y4gqgEmrxTD0lLY0X-Ww89kFPjYqcucA

### gateway 통해 actuator 호출 - busrefresh
POST 127.0.0.1:8000/user-service/actuator/busrefresh
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkNTUxZDI5My00NDNkLTRhNDEtOGE5ZS0yOTgwN2RmNTk2MmQiLCJleHAiOjE2NjIyMDkyOTF9.Npiybr47RBNQIBS4CKKZYvcuqu6-Ger2Uu2TehbmBBhlfcgZiforLHnDC9PxiXQUC3vcbp3Faqn8gh7bH729yw

### gateway 통해 actuator 호출 - busrefresh
POST 127.0.0.1:8000/actuator/busrefresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkNTUxZDI5My00NDNkLTRhNDEtOGE5ZS0yOTgwN2RmNTk2MmQiLCJleHAiOjE2NjIyMDkyOTF9.Npiybr47RBNQIBS4CKKZYvcuqu6-Ger2Uu2TehbmBBhlfcgZiforLHnDC9PxiXQUC3vcbp3Faqn8gh7bH729yw


### metrics
GET 127.0.0.1:8000/user-service/actuator/metrics
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZmM2MjBmZS04ZDMwLTRiZjktODJkNC1hZGQ0ZDllNTY4ZTIiLCJleHAiOjE2NjMyNTMwNzJ9.CH35I71lyt2FMcnqiGxehIXlz0s7vZM3CxIRwySq1zDcH2frsdd6rlVAajCT4qmKfz9BpkTtSl-JEnH1i4XgkA

### prometheus
GET 127.0.0.1:8000/user-service/actuator/prometheus
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZmM2MjBmZS04ZDMwLTRiZjktODJkNC1hZGQ0ZDllNTY4ZTIiLCJleHAiOjE2NjMyNTMwNzJ9.CH35I71lyt2FMcnqiGxehIXlz0s7vZM3CxIRwySq1zDcH2frsdd6rlVAajCT4qmKfz9BpkTtSl-JEnH1i4XgkA