### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@wooklab.org",
  "name": "test",
  "pwd": "test1234"
}

### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@google.com",
  "name": "test",
  "pwd": "test1234"
}


### get user
GET 127.0.0.1:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2ZTMzZDNjYy03YTkxLTRmYWYtODBjYi02OTUwNmZmYjdmZDkiLCJleHAiOjE2NjIxMzE3ODF9.MS65u-i_IUbvqPEO-Aea9CaZbker8bZKs5PlJaU0vyvp8t9eQKIzP3y4gqgEmrxTD0lLY0X-Ww89kFPjYqcucA


### login (별도 login end-point는 존재하지 않음, 스프링 시큐리티에서 제공)
POST 127.0.0.1:8000/user-service/login
Content-Type: application/json

{
  "email": "test@google.com",
  "password": "test1234"
}