### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@wooklab.org",
  "name": "test",
  "pwd": "test1234"
}

### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@google.com",
  "name": "test",
  "pwd": "test1234"
}


### get user
GET 127.0.0.1:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0YjI0YzEyMi1lYTJkLTQzNzEtOWU4My1mYjY1MjVmOWI2NmMiLCJleHAiOjE2NjIzODk3NzJ9.M-e6L2d40SIGBoKwuO35RBMiSmcdYQLgLD3CcCxm0CXrXNooOQ7GEwF3GWBlPF1MYOTidxIJ5seNJvE3aIPMIA


### login (별도 login end-point는 존재하지 않음, 스프링 시큐리티에서 제공)
POST 127.0.0.1:8000/user-service/login
Content-Type: application/json

{
  "email": "test@google.com",
  "password": "test1234"
}


### 계정조회
GET 127.0.0.1:8000/user-service/users/694544aa-6ce9-433d-aa25-8b22b2f2d637
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2OTQ1NDRhYS02Y2U5LTQzM2QtYWEyNS04YjIyYjJmMmQ2MzciLCJleHAiOjE2NjMwNjI0ODd9.GeN1rJJwA36QZmyAs628txObfyCHExSCgAkzzwF7IMQ3xPl5RWEclL4RXCobVbXgwjTQV8aabtdXCIx3uG7Fqg