### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@wooklab.org",
  "name": "test",
  "pwd": "test1234"
}

### create user
POST 127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email": "test@google.com",
  "name": "test",
  "pwd": "test1234"
}


### get user
GET 127.0.0.1:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiNTRhMmYzMC0zYjhkLTRiM2MtYTNhMC1hNmVkMzY5Y2RlYTkiLCJleHAiOjE2NjIzODg1ODR9.f09A55e7zXK2MqaiLYTuFXfslZwrVZSGeLvgzJN_gq5sZikFZiB5QgSvXXXkKK_0FEEQ9AuAFBqP9TLek5tjMw


### login (별도 login end-point는 존재하지 않음, 스프링 시큐리티에서 제공)
POST 127.0.0.1:8000/user-service/login
Content-Type: application/json

{
  "email": "test@google.com",
  "password": "test1234"
}


### 계정조회
GET 127.0.0.1:8000/user-service/users/b54a2f30-3b8d-4b3c-a3a0-a6ed369cdea9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiNTRhMmYzMC0zYjhkLTRiM2MtYTNhMC1hNmVkMzY5Y2RlYTkiLCJleHAiOjE2NjIzODg1ODR9.f09A55e7zXK2MqaiLYTuFXfslZwrVZSGeLvgzJN_gq5sZikFZiB5QgSvXXXkKK_0FEEQ9AuAFBqP9TLek5tjMw