server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wooklab/spring-cloud-config-sample
#          username:   # for private repo
#          passphrase: # for private repo
#          uri: file:///Users/a1101804/works/personal/github/inflearn-study/e-commerce-app/git-local-repo